### ISSUE TITLE
es6-shim.js Not included in the lib/dist/folder

### ISSUE THREAD

**Issue by goncalomarques** [swirlycheetah/generator-angular2#13]
I can't seem to make it pass the loading phase.  All I get is 404 on the es6-shim.js

**Comment by swirlycheetah** [comment]
Strange, it sounds like perhaps the default gulp task didn't complete correctly when the generator ran. 

You should have seen something similar to the image below at some point.

![screen shot 2015-03-19 at 12 47 46](https://cloud.githubusercontent.com/assets/894092/6730609/2e781cca-ce36-11e4-929e-ea9ea2217425.png)

If not then it'd be interesting to know if you can replicate this consistently when running the generator and if there's an error message, if you could provide some more information that'd be great.

In the meantime you can run `gulp` if you have gulp installed globally or `./node_modules/.bin/gulp` if not, that'll import all the required dependencies.

Any further issues let me know.

**Comment by goncalomarques** [comment]
Thanks, running `gulp` solved it for me. This was caused by my lack of experience with gulp.

**Comment by swirlycheetah** [comment]
No problem, glad you managed to get things working!
