### ISSUE TITLE
Potentially unhandled rejection [2] TypeError: Error loading "index" at http://localhost:8000/index.js

### ISSUE THREAD

**Issue by steeren** [swirlycheetah/generator-angular2#31]
I created the project and then immediately loaded it (on windows) using:
node_modules\.bin\gulp dev 

Browser window opens (chrome) and I get the following exception in the console:
Potentially unhandled rejection [2] TypeError: Error loading "index" at http://localhost:8000/index.js
Cannot convert object to primitive value
    at http://localhost:8000/lib/system.js:1:4824
    at Array.<anonymous> (http://localhost:8000/lib/angular2.js:3888:7)
    at d (http://localhost:8000/lib/system.js:1:5501)
    at d (http://localhost:8000/lib/system.js:1:5364)
    at d (http://localhost:8000/lib/system.js:1:5364)
    at l (http://localhost:8000/lib/system.js:1:4590)
    at Object.execute (http://localhost:8000/lib/system.js:1:8278)
    at o (http://localhost:8000/lib/es6-module-loader.js:7:18496)
    at p (http://localhost:8000/lib/es6-module-loader.js:7:18868)
    at j (http://localhost:8000/lib/es6-module-loader.js:7:16406)

Being totally new to ES6/Angular2/Traceure and System, I'm not sure where to begin with debugging this.

**Comment by jbonigomes** [comment]
I am getting the same thing here

**Comment by thekennysong** [comment]
Same here as well.

**Comment by npearson72** [comment]
+1

**Comment by swirlycheetah** [comment]
Taking a look at this now, apologies for the delay.

**Comment by iggied** [comment]
me too

**Comment by tarlepp** [comment]
Any updates on this issue?

**Comment by amita-trantor** [comment]
same issue

**Comment by flyingzumwalt** [comment]
+1

**Comment by lmessinger** [comment]
+1

**Comment by swirlycheetah** [comment]
Sorry all, figured I'd take the hit and use this as an opportunity to update to the latest alpha but I'm having a few issues getting everything working. Should hopefully have something published today or tomorrow.

**Comment by swirlycheetah** [comment]
Hey all, thanks for your patience with this. It should now be resolved in [0.6.0](https://www.npmjs.com/package/generator-angular2). Any issues let me know!

**Comment by lmessinger** [comment]
out of curiosity, what was the issue?

On Sun, Aug 30, 2015 at 12:21 AM, Chris Wheatley <notifications@github.com>
wrote:

> Closed #31 <https://github.com/swirlycheetah/generator-angular2/issues/31>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swirlycheetah/generator-angular2/issues/31#event-395875262>
> .
>



-- 
Lior Messinger
+1-646-3730044
+972-546-888401

**Comment by swirlycheetah** [comment]
I'm still not 100% sure. It seemed to hint at a change in a dependency somewhere but I had most pinned so perhaps it was a dependency of a dependency, either that or I pushed out a borked release from the start and never noticed :fearful:.

Either way I went ahead and updated to the latest alpha, updated to a newer version of systemjs, changed a few things and it all worked again.
