### ISSUE TITLE
Add structure documentation 

### ISSUE THREAD

**Issue by dkirrane** [swirlycheetah/generator-angular2#36]
Can you add some documentation describing the generated structure and file descriptions.

**Comment by swirlycheetah** [comment]
Good idea, will add. Where do you think would be best for it to reside?

**Comment by dkirrane** [comment]
In the README would be ideal since it'll appear on the GitHub landing page.
https://github.com/swirlycheetah/generator-angular2/blob/master/README.md
Thanks

**Comment by swirlycheetah** [comment]
I've added a basic structure. I'll keep this open for now as I plan to expand upon this when I update the project to be more in line with the current Angular2 setup.

**Comment by e-oz** [comment]
`src/all_files_here` is not a structure, sorry. Please consider to use modular structure.

**Comment by swirlycheetah** [comment]
The structure is left purposely generic to allow users to define their own preferred solution.
