### ISSUE TITLE
generator not installable

### ISSUE THREAD

**Issue by universalien** [swirlycheetah/generator-angular2#38]
generator not installable on windows 8.1, node 5.0.0, npm 3.4.0

C:\Users\...\AppData\Roaming\npm
└── (empty)

npm ERR! code 1

**Comment by swirlycheetah** [comment]
Is there any other information in the console output or an npm log file which provide any more information?

**Comment by AnneWQ** [comment]
i met the similar issue on Mac:

when install generator-angular2,error shows:

npm WARN ENOENT ENOENT: no such file or directory, open '/usr/local/lib/node_modules/generator-angular2/package.json'
npm WARN ENOENT ENOENT: no such file or directory, open '/usr/local/lib/node_modules/generator-angular2/node_modules/yeoman-assert/package.json'
npm ERR! code 1


then run  yo angular2:
You don't seem to have a generator with the name angular2 installed.

i have not found the solution.
can anyone help?

**Comment by swirlycheetah** [comment]
@AnneWQ it doesn't look like the package installed correctly, could you give me some more information on your node version, npm version and operating system and I'll investigate further.
