### ISSUE TITLE
not working your generetor

### ISSUE THREAD

**Issue by kamleshKumarVerma** [swirlycheetah/generator-angular2#40]
main angular 2 and all are not loading . in browser only showing loading 

not worked

**Comment by swirlycheetah** [comment]
Apologies for the delay @kamleshKumarVerma, which version of the generator are you using? Could you also let me know which version of node and npm you're using and what operating system you're running on and I'll investigate further.

**Comment by kamleshKumarVerma** [comment]
i am using latest version of angular2-generator . i think this is your
first version for angular 2 generator and other info is

node version - v0.10.36
npm version - 1.3.6
os - fedora 21

**Comment by swirlycheetah** [comment]
Thanks, are there any errors in the console in the browser?

**Comment by kamleshKumarVerma** [comment]
ya , it's not loading angular components

**Comment by swirlycheetah** [comment]
It may be worth trying the latest version as there's just been an update.

**Comment by Michelangelo42** [comment]
Generating and serving is fine here. node version 5.3, npm 3.3

**Comment by swirlycheetah** [comment]
Thanks @Michelangelo42. @kamleshKumarVerma going to close this now, feel free to open a new issue if you're still having problems on the latest version.
