### ISSUE TITLE
update to use ng2 beta

### ISSUE THREAD

**Issue by netlander** [swirlycheetah/generator-angular2#41]
Shouldn't this project keep up with angular2 releases?
Thanks

**Comment by michalstepien** [comment]
+1

**Comment by albertoLago** [comment]
I just pushed a beta.2 branch

**Comment by swirlycheetah** [comment]
Thanks for the PR @albertoLago, I'll take a look shortly and get things nice and up to date again.

**Comment by albertoLago** [comment]
Nothing. I'm glad to help out

**Comment by RWander** [comment]
+1

**Comment by swirlycheetah** [comment]
New release created, thanks @albertoLago!
